version: "3.9"
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6380:6379'
  database:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "Pass1234!"
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
  web:
    build:
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    entrypoint:
      - /bin/sh
      - ./entrypoint.sh
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/chatapp
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
