default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: Pass1234!
  port: 5432
  host: database

development:
  <<: *default
  database: chatapp

production:
  <<: *default
  database: chatapp
